git:
  submodules: false

language: node_js

node_js:
  - "stable"
  
notifications:
  email:
    recipients:
      - zdravecka.simona@gmail.com
    on_success: never
    on_failure: always

scripts:
  - npm install codecov -g
after_success:
  - codecov
